/**
 * Workflow schema definitions for LLM-driven dynamic workflow orchestration.
 *
 * <p>This package contains the POJOs that define the structure of workflows
 * generated by the Orchestrator LLM as structured output. These workflow plans
 * are then built into LangGraph4j StateGraphs for execution.
 *
 * <p>Key classes:
 * <ul>
 *   <li>{@link com.agentica.core.workflow.WorkflowPlan} - Complete workflow definition</li>
 *   <li>{@link com.agentica.core.workflow.WorkflowNode} - Individual agent step</li>
 *   <li>{@link com.agentica.core.workflow.WorkflowEdge} - Transition between nodes</li>
 *   <li>{@link com.agentica.core.workflow.ReplanDecision} - Orchestrator response for replanning</li>
 * </ul>
 */
package com.agentica.core.workflow;
